[package]
name = "protobuf-lite"
version = "0.1.3"
edition = "2021"
license = "Apache-2.0"
description = "decode protobuf as hashmap"
repository = "https://github.com/Redmomn/protobuf-lite"

[dependencies]
anyhow = "1.0.95"
hex = "0.4.3"
thiserror = "2.0.9"
