name: publish crate

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }} --registry crates-io
